### ISSUE TITLE
Cannot authenticate using feathers token

### ISSUE THREAD

**Issue by leuwend** [feathersjs/authentication-jwt#43] opened 2017-10-30 03:20 UTC
app runs smoothly on my local but after deploying my app to server, calling `feathersApp.authenticate()` returns error:

> Bad "options.jwtid" option. The payload already has an "jti" property.

**Comment by leuwend** [comment] 2017-10-30 04:48
i tried downgrading `feathers-authentication` to version `1.2.7` and it worked.

**Comment by daffl** [comment] 2017-10-30 05:20
Probably a regression due to https://github.com/feathersjs/authentication/pull/539 Are you overriding the `jwtid` in production?

**Comment by leuwend** [comment] 2017-10-31 00:30
i was not. it might be due to jsonwebtoken update, but i'm not sure. 

https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md

**Comment by FreeLineTM** [comment] 2017-11-01 07:27
I have the same issue but it occurs both in development and production.

**Comment by daffl** [comment] 2017-11-01 14:58
Can someone please share a reproducible example?

**Comment by FreeLineTM** [comment] 2017-11-01 15:00
I can try to set one up. Shouldn't take long. Just make a service that creates a JWT with createJWT.

**Comment by daffl** [comment] 2017-11-02 01:30
What are you calling `createJWT` for? There might be a good reason but Feathers authentication should normally not require you to ever do that directly.

**Comment by FreeLineTM** [comment] 2017-11-02 06:15
I have a service that issues JWTs to clients that call it with an API key. Reason for this is that the clients aren't real "clients", but other servers.

**Comment by subodhpareek18** [comment] 2017-11-02 06:22
@FreeLineTM why don't you use a custom auth module using passport-custom for api key authentication. I use it to completely circumvent creating JWTs. I've added it to the docs here https://github.com/feathersjs/docs/pull/885

@daffl could you please review and merge it?

**Comment by FreeLineTM** [comment] 2017-11-02 06:25
@subodhpareek18 I didn't know how to do that and the solution I'm using was a suggestion from someone else. Didn't have any better ideas myself.

**Comment by nathanbrizzee** [comment] 2017-11-03 00:00
I'm having the same problem  I was running feathers-authentication 1.2.7 on my server and everything was fine.  I upgraded today and I get the same error now. My client is using feathers-authentication 1.3.0 with no issues before the update so it's something that was introduced between 1.2.7 and 1.3.0.

**Comment by nathanbrizzee** [comment] 2017-11-03 00:24
Here is a copy of the error: (I get it when I open a new tab to the same URL.  The JWT is re-read from window.localstorage and checked to see if it's still valid.  The new window tab is the one that throws the server error, not the original one).
And my package.json diff:
![feathers-error](https://user-images.githubusercontent.com/7914937/32356447-5143f0fc-bff2-11e7-9c24-5fc48b90f92d.JPG)

info: error: authentication - Method: create: Bad "options.jwtid" option. The payload already has an "jti" property.
error:  Error: Bad "options.jwtid" option. The payload already has an "jti" property.
    at C:\code\jsapi\server\node_modules\feathers-authentication\node_modules\jsonwebtoken\sign.js:165:24
    at Array.forEach (<anonymous>)
    at Object.module.exports [as sign] (C:\code\jsapi\server\node_modules\feathers-authentication\node_modules\jsonwebtoken\sign.js:161:35)
    at C:\code\jsapi\server\node_modules\feathers-authentication\lib\utils.js:54:28
    at Promise (<anonymous>)
    at Authenticator.createJWT (C:\code\jsapi\server\node_modules\feathers-authentication\lib\utils.js:46:10)
    at Object.create (C:\code\jsapi\server\node_modules\feathers-authentication\lib\service.js:48:28)
    at C:\code\jsapi\server\node_modules\feathers-hooks\lib\hooks.js:101:31
    at Promise (<anonymous>)
    at C:\code\jsapi\server\node_modules\feathers-hooks\lib\hooks.js:85:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by daffl** [comment] 2017-11-03 02:03
I have a fix in https://github.com/feathersjs/authentication/pull/600 which should be released shortly.

**Comment by daffl** [comment] 2017-11-03 15:48
Closed via #600

**Closed** 2017-11-04 22:00 UTC

**Comment by leuwend** [comment] 2017-11-07 11:56
thanks @daffl! 💯

**Comment by nathanbrizzee** [comment] 2017-11-08 16:48
It now works for me.  Thank you so much for the quick turn around!
